
NAME: ''
OUTPUT_DIR: './output/ERA_for_CAM/imagenet/ResNet18/Base0/task2/oldModel-gradCAM-2'
SHOW_STEP: 50
SAVE_STEP: 100
VALID_STEP: 25
INPUT_SIZE: (224, 224)
COLOR_SPACE: 'RGB'
CPU_MODE: False
use_best_model: False
#task1_MODEL: "/data0/user/kcli/CL_research/DataFreeCL-V2/output/ABD_for_CAM/imagenet/ResNet18/Base0/task2/test2/models/ABD_FCTM_imagenet_vis.pth"
#task1_MODEL: "/data0/user/kcli/CL_research/DataFreeCL-V2/output/ABD_for_CAM/imagenet/ResNet18/Base0/task2/test1/models/base_latest_model.pth"
#task1_MODEL: "/data0/user/kcli/CL_research/DataFreeCL-V2/output/ERA-newmodel/CAM-imagenet/ResNet18/Base0/task2/test2/models/base_latest_model.pth"
#task1_MODEL: "/data0/user/kcli/CL_research/DataFreeCL-V2/output/ERA-newmodel/CAM-imagenet/ResNet18/Base0/task2/test2/models/2_latest_new_model.pth"
#task1_MODEL: "/data0/user/kcli/CL_research/DataFreeCL-V2/output/ERA-newmodel/CAM-imagenet/ResNet18/Base0/task2/test2/models/2_latest_model.pth"
#task1_MODEL: "/data0/user/kcli/CL_research/DataFreeCL-V2/output/EARS_DFCL/finetune/imagenet-vis/ResNet18/Base0/task2/FCTM-ABD/model-LwF-RTKD-ABD/test1/models/latest_FCTM.pth"
task1_MODEL: "/data0/user/kcli/CL_research/DataFreeCL-V2/output/EARS_DFCL/finetune/imagenet-vis/ResNet18/Base0/task2/FCTM-ABD/model-LwF-RTKD-ABD/test1/models/base_latest_model.pth"
pre_model: "/data0/user/kcli/CL_research/DataFreeCL-V2/output/EARS_DFCL/finetune/imagenet-vis/ResNet18/Base0/task2/FCTM-ABD/model-LwF-RTKD-ABD/test1/models/base_latest_model.pth"
pretrained_MODEL: ""
use_base_half: False
checkpoints: ''
save_model: False
use_Contra_train_transform: False
train_first_task: False

seed: 0
trainer_name: "ABD_for_CAM"
# ----- DATASET BUILDER -----
DATASET:
  dataset: "Local_Datasets_Split"
  dataset_name: "imagenet"                  #mnist, mnist28, CIFAR10, CIFAR100, imagenet, svhn
  data_json_file: '/data0/user/kcli/imagenet_vis_2.json'
  data_root: "/data0/share/datasets/ImageNet/"
  all_classes: 4
  all_tasks: 2
  split_seed: 0
# ----- resume -----

RESUME:
  use_resume: False
  resumed_model_path: ""

# ----- pre-train setting -----
PRETRAINED:
  use_pretrained_model: False
  MODEL: ""


# ----- extractor BUILDER -----
extractor:
  TYPE: 'resnet18'
  rate: 1.
  output_feature_dim: 512


#----- model -----
model:
  kd_lambda: 1e-1
  TRAIN:
    BATCH_SIZE: 64
    MAX_EPOCH: 110
    NUM_WORKERS: 4
    SHUFFLE: True
    OPTIMIZER:
      TYPE: 'SGD'
      BASE_LR: 0.1
      MOMENTUM: 0.9
      WEIGHT_DECAY: 1e-4
    LR_SCHEDULER:
      TYPE: 'warmup'
      LR_STEP:  [ 35, 65, 85, 95 ]
      LR_FACTOR: 0.1
      WARM_EPOCH: 5

generator:
  gen_model_name: "IMNET_GEN"
  generator_iter: 10000
  batch_size: 64
  deep_inv_params: [1.e-3, 50, 1.0e-3, 1000] # generator_lr, r_feature_weight, pr_scale, content_temp 1e-3 5e1 1e-3 1e3

#----- FCTM -----
FCTM:
  # classification loss:
  ce_lambda: 0.5
  addCls_lambda: 1.
  allcls_lambda: 1.
  all_cls_LOSS_TYPE: "CE"
  add_cls_LOSS_TYPE: "CE"

  # logit KD:
  T: 2.
  hkd_lambda: 0.15
  kd_lambda: 1.

  # rkd:
  rkd_lambda: 0.5

  use_FCN: True
  FCN:
    in_feature_dim: 1024
    out_feature_dim: 512
    layer_nums: 3
    hidden_layer_rate: 2
    last_hidden_layer_use_relu: True
  TRAIN:
    tradeoff_rate: 1.
    BATCH_SIZE: 64
    MAX_EPOCH: 110
    #MAX_EPOCH: 160
    NUM_WORKERS: 4
    SHUFFLE: True
    OPTIMIZER:
      TYPE: 'SGD'
      BASE_LR: 0.1
      MOMENTUM: 0.9
      WEIGHT_DECAY: 1e-4
    LR_SCHEDULER:
      #TYPE: "CosineAnnealing"
      TYPE: 'warmup'
      LR_STEP: [ 35, 65, 85, 95 ]
      LR_FACTOR: 0.1
      WARM_EPOCH: 5



