
NAME: ''
OUTPUT_DIR: './output/EARS_DFCL/imagenet100/ResNet18/BaseHalf/task5/test1'
SHOW_STEP: 50
SAVE_STEP: 100
VALID_STEP: 25
INPUT_SIZE: (224, 224)
COLOR_SPACE: 'RGB'
CPU_MODE: False
use_best_model: False
#task1_MODEL: "/data0/user/kcli/CL_research/DataFreeCL-V2/output/EARS_DFCL/finetune/imagenet-vis/ResNet18/Base0/task2/FCTM-ABD/model-LwF-RTKD-ABD/test1/models/base_latest_model.pth"
#task1_MODEL: "/data0/user/kcli/CL_research/QuintCDKD/reuse-model/imagent100-base0-task10-base_latest_model.pth"
task1_MODEL: "/data0/user/kcli/CL_research/QuintCDKD/reuse-model/imagent100-basehalf-task10-base_latest_model.pth"
#task1_MODEL: "/home/likunchi/reuse-model/imagent100-base0-task10-base_latest_model.pth"
pretrained_MODEL: ""
use_base_half: True
checkpoints: ''
save_model: True
use_Contra_train_transform: False
train_first_task: False

seed: 0
trainer_name: "EARS_DFCL"
# ----- DATASET BUILDER -----

DATASET:
  dataset: "Local_Datasets_Split_Per_Class"
  dataset_name: "imagenet"                  #mnist, mnist28, CIFAR10, CIFAR100, imagenet, svhn
  data_json_file: '/data0/user/kcli/Datasets/imagenet/podnet_imagenet100_forCL.json'
  data_root: "/data0/share/datasets/ImageNet/"
#  data_json_file: '/home/likunchi/Datasets/imagenet/podnet_imagenet100_forCL.json'
#  data_root: "/home/likunchi/Datasets/ImageNet/"
  all_classes: 100
  all_tasks: 10
  split_seed: 0
  val_length: 0
# ----- resume -----

RESUME:
  use_resume: False
  resumed_model_path: ""

# ----- pre-train setting -----
PRETRAINED:
  use_pretrained_model: False
  MODEL: ""


# ----- extractor BUILDER -----
extractor:
  TYPE: 'resnet18'
  #TYPE: "resnet34"
#  TYPE: "res32_cifar"
  rate: 1.
  output_feature_dim: 512

generator:
  gen_model_name: "IMNET_GEN"
  generator_iter: 10000
  batch_size: 64
  deep_inv_params: [1.e-3, 50, 1.0e-3, 1000] # generator_lr, r_feature_weight, pr_scale, content_temp 1e-3 5e1 1e-3 1e3

#----- model -----
model:
#cls loss:
  softTarget_lambda: 1.
#  cls_type: "softTarget"
#  cls_type: "adjusted_logit"
#  cls_type: "FTCE"
  cls_type: "LwF"

#logit KD:
  T: 2.
#  KD_type: "ReKD"
  KD_type: "RTKD"
  kd_lambda: 1.

# feature KD
  fkd_lambda: 1.
  use_cls_loss: True
  use_ABD_loss: False
  featureKD:
    use_featureKD: True
    use_ABD_KD: True

  TRAIN:
    BATCH_SIZE: 64
    MAX_EPOCH: 110
    NUM_WORKERS: 4
    SHUFFLE: True
    OPTIMIZER:
      TYPE: 'SGD'
      BASE_LR: 0.1
      MOMENTUM: 0.9
      WEIGHT_DECAY: 1e-4
    LR_SCHEDULER:
      TYPE: 'warmup'
      LR_STEP: [ 35, 65, 85, 95 ]
#      LR_STEP: [80, 120]
      LR_FACTOR: 0.1
      WARM_EPOCH: 5
  finetune:
    MAX_EPOCH: 100
    BATCH_SIZE: 64
    SHUFFLE: True
    NUM_WORKERS: 4
    # ----- OPTIMIZER -----
    BASE_LR: 0.005
    TYPE: "SGD"
    MOMENTUM: 0.9
    WEIGHT_DECAY: 1e-4
    # ----- LR_SCHEDULER -----
    LR_TYPE: "multistep"
    LR_STEP: [ 50, 80 ]
    LR_FACTOR: 0.1
    WARM_EPOCH: 5


#----- FCTM -----
FCTM:
  # classification loss:
  use_ABD_KD: True
  ce_lambda: 0.5
  addCls_lambda: 1.
  allcls_lambda: 1.
  all_cls_LOSS_TYPE: "CE"
  add_cls_LOSS_TYPE: "CE"

  # logit KD:
  T: 2.
  hkd_lambda: 0.15
  kd_lambda: 1.

  # rkd:
  rkd_lambda: 0.5

  use_FCN: True
  FCN:
    in_feature_dim: 1024
    out_feature_dim: 512
    layer_nums: 3
    hidden_layer_rate: 2
    last_hidden_layer_use_relu: True
  TRAIN:
    tradeoff_rate: 1.
    BATCH_SIZE: 64
    MAX_EPOCH: 110
    #MAX_EPOCH: 160
    NUM_WORKERS: 4
    SHUFFLE: True
    OPTIMIZER:
      TYPE: 'SGD'
      BASE_LR: 0.1
      MOMENTUM: 0.9
      WEIGHT_DECAY: 1e-4
    LR_SCHEDULER:
      #TYPE: "CosineAnnealing"
      TYPE: 'warmup'
      LR_STEP: [ 35, 65, 85, 95 ]
      LR_FACTOR: 0.1
      WARM_EPOCH: 5



