
NAME: ''
OUTPUT_DIR: './output/FCS/tiny/ResNet18/BaseHalf/task5/test3'
SHOW_STEP: 50
SAVE_STEP: 100
VALID_STEP: 25
INPUT_SIZE: (64, 64)
COLOR_SPACE: 'RGB'
CPU_MODE: False
use_best_model: False
task1_MODEL: ""
pretrained_MODEL: ""
use_base_half: True
checkpoints: ''
save_model: True
use_Contra_train_transform: True
train_first_task: True
seed: 0
# ----- DATASET BUILDER -----

DATASET:
  dataset: "Local_Datasets_Split"
  dataset_name: "tiny_imagenet"                  #mnist, mnist28, CIFAR10, CIFAR100, imagenet, svhn imagenet
#  data_json_file: '/data0/user/kcli/Datasets/tiny-imagenet-200/tiny_imagenet_200_dataset_train_val.json'
#  data_root: "/data0/user/kcli/Datasets/tiny-imagenet-200"
  data_json_file: '/home/likunchi/Datasets/tiny-imagenet-200/tiny_imagenet_200_dataset_train_val.json'
  data_root: "/home/likunchi/Datasets/tiny-imagenet-200"
  all_classes: 200
  all_tasks: 10
  split_seed: 0
  val_length: 0

# ----- exemplar_manager -----
exemplar_manager:
  store_original_imgs: True
  memory_budget: 0
  mng_approach: "herding"      #herding, random, kmeans
  norm_exemplars: True
  centroid_order: "herding"   #herding, distance, None
  fixed_exemplar_num: -1
# ----- resume -----

RESUME:
  use_resume: False
  resumed_model_path: ""

# ----- pre-train setting -----
PRETRAINED:
  use_pretrained_model: False
  MODEL: ""


# ----- extractor BUILDER -----
extractor:
  TYPE: "resnet18_cbam"
#  TYPE: 'resnet18'


#----- model -----
model:

  temp: 0.1

  contrast:
    lambda_contrast: 0.1
    contrast_T: 0.07

  transfer:
    lambda_transfer: 1.

  fkd:
    lambda_fkd: 1.

  proto:
    lambda_proto: 10.

#  TRAIN:
#    BATCH_SIZE: 64
#    MAX_EPOCH: 110
#    NUM_WORKERS: 4
#    SHUFFLE: True
#    OPTIMIZER:
#      TYPE: 'SGD'
#      BASE_LR: 0.001
#      MOMENTUM: 0.9
#      WEIGHT_DECAY: 2e-4
#    LR_SCHEDULER:
#      LR_STEP: 45
#      LR_FACTOR: 0.1

  TRAIN:
    BATCH_SIZE: 128
    MAX_EPOCH: 250
    NUM_WORKERS: 4
    SHUFFLE: True
    OPTIMIZER:
      TYPE: 'SGD'
      BASE_LR: 0.1
      MOMENTUM: 0.9
      WEIGHT_DECAY: 1e-4
    LR_SCHEDULER:
      TYPE: 'warmup'
      STEP_SIZE: 45
      LR_STEP:  [75, 125, 175, 225]
      LR_FACTOR: 0.1
      WARM_EPOCH: 5



