
NAME: ''
OUTPUT_DIR: './output/FeCAM/imagenet100/ResNet18/Base0/task10/debug'
SHOW_STEP: 50
SAVE_STEP: 100
VALID_STEP: 25
INPUT_SIZE: (3, 224, 224)
COLOR_SPACE: 'RGB'
CPU_MODE: False
use_best_model: False
#task1_MODEL: "/data0/user/kcli/CL_research/QuintCDKD/reuse-model/imagent100-base0-task10-base_latest_model.pth"
task1_MODEL: "/home/likunchi/reuse-model/imagent100-base0-task10-base_latest_model.pth"
use_base_half: False
checkpoints: ''
save_model: False
use_Contra_train_transform: False
approach: "FeCAM"
train_first_task: False
seed: 0
# ----- DATASET BUILDER -----

DATASET:
  dataset: "Local_Datasets_Split_Per_Class"
  dataset_name: "imagenet"                    #mnist, mnist28, CIFAR10, CIFAR100, imagenet, svhn imagenet
#  data_json_file: '/data0/user/kcli/Datasets/imagenet/podnet_imagenet100_forCL.json'
#  data_root: "/data0/share/datasets/ImageNet/"
  data_json_file: '/home/likunchi/Datasets/imagenet/podnet_imagenet100_forCL.json'
  data_root: "/home/likunchi/Datasets/ImageNet/"
  all_classes: 100
  all_tasks: 10
  split_seed: 0
  val_length: 0

# ----- resume -----

RESUME:
  use_resume: False
  resumed_file: ""
  resumed_model_path: ""
  resumed_bias_layer_path: ""


# ----- extractor BUILDER -----
extractor:
  TYPE: 'resnet18'
  rate: 1.
  output_feature_dim: 512

# ----- classifier BUILDER -----
classifier:
  bias: True
#  classifier_type: "CosineLinear"
  classifier_type: "linear"
  #LOSS_TYPE: "CrossEntropy"
  LOSS_TYPE: "CrossEntropy"
#  LOSS_TYPE: "bsce"

#----- model -----
model:
  EPSILON: 1e-8
  shrink: True
  norm_cov: True
  alpha1: 1.
  alpha2: 1.
  beta: 0.5
  eeil_finetune_train:
    BATCH_SIZE: 128
    MAX_EPOCH: 50
    NUM_WORKERS: 4
    SHUFFLE: True



