
NAME: ''
OUTPUT_DIR: './output/FARM-EFCL/imagenet100/ResNet18/Base0/task10/tau-1.25/finetune/test1'
SHOW_STEP: 50
SAVE_STEP: 100
VALID_STEP: 25
INPUT_SIZE: (224, 224)
COLOR_SPACE: 'RGB'
CPU_MODE: False
use_best_model: False
task1_MODEL: "/home/likunchi/reuse-model/imagent100-base0-task10-base_latest_model.pth"
pretrained_MODEL: ""
use_base_half: False
checkpoints: ''
save_model: True
use_Contra_train_transform: False
train_first_task: False

seed: 0
trainer_name: "progressive_DFCL"
# ----- DATASET BUILDER -----

DATASET:
  dataset: "Local_Datasets_Split_Per_Class"
  dataset_name: "imagenet"                    #mnist, mnist28, CIFAR10, CIFAR100, imagenet, svhn imagenet
#  data_json_file: '/data0/user/kcli/Datasets/imagenet/podnet_imagenet100_forCL.json'
#  data_root: "/data0/share/datasets/ImageNet/"
  data_json_file: '/home/likunchi/Datasets/imagenet/podnet_imagenet100_forCL.json'
  data_root: "/home/likunchi/Datasets/ImageNet/"
  all_classes: 100
  all_tasks: 10
  split_seed: 0
  val_length: 0
# ----- resume -----

RESUME:
  use_resume: False
  resumed_model_path: ""

# ----- pre-train setting -----
PRETRAINED:
  use_pretrained_model: False
  MODEL: ""


# ----- extractor BUILDER -----
extractor:
  TYPE: 'resnet18'
  #TYPE: "resnet34"
#  TYPE: "res32_cifar"
  rate: 1.
  output_feature_dim: 512

generator:
  gen_model_name: "IMNET_GEN"
  generator_iter: 10000
  batch_size: 64
  deep_inv_params: [1.e-3, 50, 1.0e-3, 1000] # generator_lr, r_feature_weight, pr_scale, content_temp 1e-3 5e1 1e-3 1e3

#----- model -----

model:
  T: 2.
  tau: 1.25
#  cls_type: "LwF"
#  KD_type: "RTKD"
#  cls_type: "BSCE-class"
  cls_type: "null"
  KD_type: "LAKD-class"
#  KD_type: "BKD"
#  KD_type: "TKD"
#  KD_type: "null"
  kd_lambda: 1.

# feature KD
  fkd_lambda: 0.2
  use_featureKD: True

  TRAIN:
    BATCH_SIZE: 64
    MAX_EPOCH: 110
    NUM_WORKERS: 8
    SHUFFLE: True
    OPTIMIZER:
      TYPE: 'SGD'
      BASE_LR: 0.1
      MOMENTUM: 0.9
      WEIGHT_DECAY: 1e-4
    LR_SCHEDULER:
      TYPE: 'warmup'
      LR_STEP:  [ 35, 65, 85, 95 ]
      LR_FACTOR: 0.1
      WARM_EPOCH: 5
  finetune:
    MAX_EPOCH: 60
    BATCH_SIZE: 64
    SHUFFLE: True
    NUM_WORKERS: 4
    # ----- OPTIMIZER -----
    BASE_LR: 0.005
    TYPE: "SGD"
    MOMENTUM: 0.9
    WEIGHT_DECAY: 1e-4
    # ----- LR_SCHEDULER -----
    LR_TYPE: "multistep"
    LR_STEP: [ 30, 50 ]
    LR_FACTOR: 0.1
    WARM_EPOCH: 5





#----- new_model -----
new_model:
  loss_type: "ABD"
  T: 2.
  kd_lambda: 1.

  TRAIN:
    BATCH_SIZE: 64
    MAX_EPOCH: 110
    NUM_WORKERS: 8
    SHUFFLE: True
    OPTIMIZER:
      TYPE: 'SGD'
      BASE_LR: 0.1
      MOMENTUM: 0.9
      WEIGHT_DECAY: 1e-4
    LR_SCHEDULER:
      #TYPE: "CosineAnnealing"
      TYPE: 'warmup'
      LR_STEP:  [ 35, 65, 85, 95 ]
      LR_FACTOR: 0.1
      WARM_EPOCH: 5